### ISSUE TITLE
How do you use snippets?

### ISSUE THREAD

**Issue by davision** [nateomedia/vscode-foundation6-snippets#1]
Installed the extension, but I can not find any documentation or examples how to use it. Can you provide any?

**Comment by nateomedia** [comment]
Just start typing. The extension will offer suggestions for autocompleting any Foundation 6 code you include. That’s all snippets are — shortcuts for coding faster.

**Comment by davision** [comment]
So it just suggests class names? Shouldn't be creating actual markup out of it? It requires any additional configuration file?

**Comment by nateomedia** [comment]
It should suggest class names, yes. Once you select a class name it will insert the full code block with tabbable fields for customizing.

**Comment by nateomedia** [comment]
https://code.visualstudio.com/docs/editor/userdefinedsnippets

**Comment by davision** [comment]
Ok. I tried on .html and .hbs files, but it did't work at all. No code with tabbable fields.

**Comment by nateomedia** [comment]
Okay. Not sure there’s much I can do to help. Snippet functionality is built into VS Code — all this extension does is provide definitions for Foundation 6. It should work for html and scss files. Try reinstalling the program and/or reviewing your other extensions or preferences for conflicts.

**Comment by davision** [comment]
Thank you, will try one more time! Hope it works.
